apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wallabag.fullname" . }}
  labels:
    {{- include "wallabag.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "wallabag.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "wallabag.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            {{- include "wallabag.probe" .Values.livenessProbe | nindent 14 }}
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            {{- include "wallabag.probe" .Values.readinessProbe | nindent 14 }}
          {{- end }}
          {{- if .Values.startupProbe.enabled }}
          startupProbe:
            {{- include "wallabag.probe" .Values.startupProbe | nindent 14 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ include "wallabag.fullname" . }}-configmap
            {{- if .Values.externalDatabase.existingSecret }}
            - secretRef:
                name: {{ .Values.externalDatabase.existingSecret }}
            {{- else }}
            - secretRef:
                name: {{ include "wallabag.fullname" . }}-db-credentials
            {{- end }}
            {{- if .Values.externalRedis.existingSecret }}
            - secretRef:
                name: {{ .Values.externalRedis.existingSecret }}
            {{- else if or .Values.redis.enabled .Values.externalRedis.host }}
            - secretRef:
                name: {{ include "wallabag.fullname" . }}-redis-credentials
            {{- end }}
            {{- if .Values.externalDatabase.existingAdminSecret }}
            - secretRef:
                name: {{ .Values.externalDatabase.existingAdminSecret }}
                optional: true
            {{- else if include "wallabag.use-db-admin" . }}
            - secretRef:
                name: {{ include "wallabag.fullname" . }}-db-admin
                optional: true
            {{- end }}
          volumeMounts:
            - name: entrypoint-script
              mountPath: /entrypoint.sh
              subPath: entrypoint.sh
              readOnly: true
            {{- if .Values.persistence.enabled }}
            - name: data
              mountPath: /var/www/wallabag/data
            {{- end }}
            {{- range .Values.persistence.extraVolumes }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
            {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: entrypoint-script
          configMap:
            name: {{ include "wallabag.fullname" . }}-entrypoint
            defaultMode: 0755
        {{- if .Values.persistence.enabled }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "wallabag.fullname" . }}-pvc
        {{- end }}
        {{- range .Values.persistence.extraVolumes }}
        - name: {{ .name }}
          persistentVolumeClaim:
            claimName: {{ .name }}
        {{- end }}
