{{- if not .Values.externalDatabase.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wallabag.fullname" . }}-db-credentials
  labels:
    {{- include "wallabag.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.mariadb.enabled }}
  SYMFONY__ENV__DATABASE_HOST: {{ include "mariadb.primary.fullname" .Subcharts.mariadb | b64enc | quote }}
  {{- include "wallabag.db-credentials" .Values.mariadb.auth | nindent 2 }}
  {{- else if .Values.externalDatabase.host }}
  SYMFONY__ENV__DATABASE_HOST: {{ .Values.externalDatabase.host | b64enc | quote }}
  {{- include "wallabag.db-credentials" .Values.externalDatabase | nindent 2 }}
  {{- end }}
{{- end }}
---
{{- if and (not .Values.externalRedis.existingSecret) (or .Values.redis.enabled .Values.externalRedis.host) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wallabag.fullname" . }}-redis-credentials
  labels:
    {{- include "wallabag.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.redis.enabled }}
  SYMFONY__ENV__REDIS_HOST: {{ include "common.names.fullname" .Subcharts.redis | b64enc | quote }}
  {{- include "wallabag.redis-credentials" .Values.redis.auth | nindent 2 }}
  {{- else if .Values.externalRedis.host }}
  SYMFONY__ENV__REDIS_HOST: {{ .Values.externalRedis.host | b64enc | quote }}
  {{- include "wallabag.redis-credentials" .Values.externalRedis | nindent 2 }}
  {{- end }}
{{- end }}

{{- if or (and .Values.mariadb.enabled .Values.mariadb.auth.rootPassword) .Values.externalDatabase.rootPassword }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wallabag.fullname" . }}-db-admin
  labels:
    {{- include "wallabag.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.mariadb.enabled }}
  MYSQL_ROOT_PASSWORD: {{ .Values.mariadb.auth.rootPassword | b64enc | quote }}
  {{- else }}
  MYSQL_ROOT_PASSWORD: {{ .Values.externalDatabase.rootPassword | b64enc | quote }}
  {{- end }}
{{- end }}
