{{- if not .Values.externalDatabase.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wallabag.fullname" . }}-db-credentials
  labels:
    {{- include "wallabag.labels" . | nindent 4 }}
type: Opaque
data:
  {{- $dbType := include "wallabag.database-type" . -}}
  {{- if eq $dbType "mariadb" }}
  SYMFONY__ENV__DATABASE_HOST: {{ include "mariadb.primary.fullname" .Subcharts.mariadb | b64enc | quote }}
  {{- include "wallabag.db-credentials" .Values.mariadb.auth | nindent 2 }}
  {{- else if eq $dbType "postgresql" }}
  SYMFONY__ENV__DATABASE_HOST: {{ include "postgresql.v1.primary.fullname" .Subcharts.postgresql | b64enc | quote }}
  {{- include "wallabag.db-credentials" .Values.postgresql.auth | nindent 2 }}
  {{- else if eq $dbType "external" }}
  SYMFONY__ENV__DATABASE_HOST: {{ .Values.externalDatabase.host | b64enc | quote }}
  {{- include "wallabag.db-credentials" .Values.externalDatabase | nindent 2 }}
  {{- end }}
{{- end }}
---
{{- if and (not .Values.externalRedis.existingSecret) (or .Values.redis.enabled .Values.externalRedis.host) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wallabag.fullname" . }}-redis-credentials
  labels:
    {{- include "wallabag.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.redis.enabled }}
  SYMFONY__ENV__REDIS_HOST: {{ include "common.names.fullname" .Subcharts.redis | b64enc | quote }}
  {{- include "wallabag.redis-credentials" .Values.redis.auth | nindent 2 }}
  {{- else if .Values.externalRedis.host }}
  SYMFONY__ENV__REDIS_HOST: {{ .Values.externalRedis.host | b64enc | quote }}
  {{- include "wallabag.redis-credentials" .Values.externalRedis | nindent 2 }}
  {{- end }}
{{- end }}

{{- if include "wallabag.use-db-admin" . }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wallabag.fullname" . }}-db-admin
  labels:
    {{- include "wallabag.labels" . | nindent 4 }}
type: Opaque
data:
  {{- $dbType := include "wallabag.database-type" . -}}
  {{- if eq $dbType "postgresql" }}
  {{/* Postgres admin user could'nt be changed in Bitnami chart */}}
  POSTGRES_USER: {{ "postgres" | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.auth.postgresPassword | b64enc | quote }}
  {{- else }}
  {{- $password := "" -}}
  {{- if eq $dbType "mariadb" }}
  {{- $password = .Values.mariadb.auth.rootPassword -}}
  {{- else if eq $dbType "external" }}
  {{- $password = .Values.externalDatabase.rootPassword -}}
  {{- end }}
  {{- if and (eq $dbType "external") (eq .Values.externalDatabase.driver "pdo_pgsql") }}
  POSTGRES_USER: {{ .Values.externalDatabase.rootUser | default "postgres" | b64enc | quote }}
  POSTGRES_PASSWORD: {{ $password | b64enc | quote }}
  {{- else }}
  MYSQL_ROOT_PASSWORD: {{ $password | b64enc | quote }}
  {{- end }}
  {{- end }}
{{- end }}
